#
# Makefile for industrial I/O Light sensors
#
GCOV_PROFILE := y

obj-$(CONFIG_SENSORS_TSL2563)	+= tsl2563.o
obj-$(CONFIG_SENSORS_ISL29018)	+= isl29018.o
obj-$(CONFIG_TSL2583)	+= tsl2583.o
obj-$(CONFIG_SENSORS_ISL29023)  += isl29023.o
obj-$(CONFIG_SENSORS_ISL29028)	+= isl29028.o
obj-$(CONFIG_SENSORS_LTR558)	+= ltr558als.o
